services:
  - type: web
    name: kixiegpt
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_server_cloud:app --bind 0.0.0.0:$PORT
    plan: free
    env:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PIP_UPGRADE_STRATEGY
        value: only-if-needed
    envVars:
      - key: HUBSPOT_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: KIXIE_API_KEY
        sync: false
      - key: KIXIE_BUSINESS_ID
        sync: false
      - key: SENDER_EMAIL
        sync: false